_wandb:
    value:
        cli_version: 0.28.0
        e:
            mhcanip1f6svmosp3s2zn9kg7w88j3wo:
                args:
                    - --config
                    - configs/s2mel_zipformer.yaml
                    - --train-speechdata-dir
                    - gs://noiz-taiwan-audio-data/preprocessed/vctk
                    - --speechdata-cache-dir
                    - /tmp/semantic2any-speechdata-vctk
                    - --output-dir
                    - exp/s2mel_zipformer-vctk
                codePath: trainers/train_s2mel_zipformer.py
                codePathLocal: trainers/train_s2mel_zipformer.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "468731568128"
                        used: "372296753152"
                email: haoyuanhuang22@gmail.com
                executable: /mnt/data_sdd/hhy/noiz-tts/semantic2any/.venv/bin/python
                git:
                    commit: 16ec8e2691dd041e9c9a395a885babcf179a0dcd
                    remote: git@github.com:Ksuriuri/semantic2any.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "48305799168"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-f096c53c-9ff3-f76e-4199-8ad00b353f2f
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "48305799168"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-b69a4520-8249-0949-a502-040d23649d3f
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "48305799168"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-8282f6f6-6d1a-a407-73be-d1c113b6deb8
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "48305799168"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-feb51bc8-f165-bceb-91bc-925fc1ed39b6
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "48305799168"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-055a536c-454c-fdfe-fe50-59fd3cb4e0c3
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "48305799168"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-faef1935-1a9a-3d89-5a42-18ab03a9b90c
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "51527024640"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-cb1ac9e6-fe08-d5d0-e5e7-724ea7d42063
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "48305799168"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-9d9f90fb-20a4-4b2d-061c-6db83d5c1584
                host: E0904
                memory:
                    total: "540899229696"
                os: Linux-5.15.0-164-generic-x86_64-with-glibc2.35
                program: /mnt/data_sdd/hhy/noiz-tts/semantic2any/trainers/train_s2mel_zipformer.py
                python: CPython 3.13.9
                root: /mnt/data_sdd/hhy/noiz-tts/semantic2any
                startedAt: "2026-07-07T18:52:51.921431Z"
                writerId: mhcanip1f6svmosp3s2zn9kg7w88j3wo
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
            "2":
                - 1
                - 11
                - 49
                - 71
            "3":
                - 13
            "4": 3.13.9
            "5": 0.28.0
            "6": 4.52.1
            "12": 0.28.0
            "13": linux-x86_64
data:
    value:
        max_audio_seconds: 20
        max_prompt_seconds: 5
        min_generated_frames: 8
        min_prompt_seconds: 1
        num_workers: 2
        prefetch_factor: 2
        sample_rate_16k: 16000
        sample_rate_mel: 22050
        semantic_fps: 25
        speechdata_cache_dir: /tmp/semantic2any-speechdata-vctk
        train_jsonl: ""
        train_speechdata_dir: gs://noiz-taiwan-audio-data/preprocessed/vctk
        valid_jsonl: ""
        valid_speechdata_dir: ""
paths:
    value:
        campplus_ckpt: campplus/campplus_cn_common.bin
        indextts_root: /mnt/data_sdd/hhy/index-tts
        model_dir: /mnt/data_sdd/hhy/index-tts/checkpoints
        semantic_codec_ckpt: ""
        w2v_bert_dir: w2v-bert-2.0
        w2v_stat: wav2vec2bert_stats.pt
preprocess_params:
    value:
        spect_params:
            fmax: None
            fmin: 0
            hop_length: 256
            n_fft: 1024
            n_mels: 80
            win_length: 1024
        sr: 22050
s2mel:
    value:
        DiT:
            content_dim: 512
            in_channels: 80
            zero_prompt_speech_token: false
        ZipFormer:
            class_dropout_prob: 0.1
            cnn_module_kernel:
                - 31
                - 15
                - 7
                - 15
                - 31
            condition_dropout_prob: 0.1
            downsampling_factor:
                - 1
                - 2
                - 4
                - 2
                - 1
            feedforward_dim: 1536
            hidden_dim: 512
            num_heads: 4
            num_layers:
                - 2
                - 2
                - 4
                - 4
                - 4
            pos_dim: 48
            pos_head_dim: 4
            query_head_dim: 32
            style_condition: true
            time_embed_dim: 192
            use_conv: true
            value_head_dim: 12
        dit_type: ZipFormer
        inference_cfg_rate: 0.7
        inference_steps: 25
        length_ratio: 3.44
        length_regulator:
            channels: 512
            content_codebook_size: 8192
            f0_condition: false
            in_channels: 1024
            is_discrete: false
            n_codebooks: 1
            n_f0_bins: 512
            quantizer_dropout: 0
            sampling_ratios:
                - 1
                - 1
                - 1
                - 1
        reg_loss_type: l1
        style_encoder:
            dim: 192
        use_gpt_latent: false
seed:
    value: 1234
train:
    value:
        batch_size: 4
        epochs: 10
        grad_accumulation: 1
        grad_clip: 1
        keep_last: 5
        learning_rate: 0.0001
        log_interval: 20
        max_steps: 0
        mixed_precision: fp16
        no_wandb: false
        output_dir: exp/s2mel_zipformer-vctk
        resume_from: ""
        save_interval: 10000
        valid_interval: 500
        wandb_entity: haoyuanhuang22-jcxy
        wandb_project: semantic2mel
        wandb_run_name: s2mel_zipformer-vctk
        warmup_steps: 1000
        weight_decay: 0.01
