seed: 1234

paths:
  indextts_root: /mnt/data_sdd/hhy/index-tts
  model_dir: /mnt/data_sdd/hhy/index-tts/checkpoints/IndexTTS-2-vLLM
  semantic_codec_ckpt: ""
  campplus_ckpt: campplus/campplus_cn_common.bin
  w2v_bert_dir: w2v-bert-2.0
  w2v_stat: wav2vec2bert_stats.pt

data:
  train_jsonl: ""
  valid_jsonl: ""
  train_speechdata_dir: ""
  valid_speechdata_dir: ""
  speechdata_cache_dir: /mnt/data_sdd/hhy/noiz-tts/semantic2any/.cache/speechdata
  max_audio_seconds: 30.0
  pair_same_speaker: true
  random_split_audio: false
  max_pair_seconds: 30.0
  min_pair_prompt_seconds: 3.0
  min_prompt_seconds: 1.0
  max_prompt_seconds: 5.0
  min_target_seconds: null
  min_generated_frames: 8
  semantic_fps: 50.0
  sample_rate_16k: 16000
  sample_rate_mel: 22050
  num_workers: 8
  prefetch_factor: 2
  decode_audio_in_worker: false
  skip_audio_errors: false
  feature_batch_size: 16

preprocess_params:
  sr: 22050
  spect_params:
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    n_mels: 80
    fmin: 0
    fmax: "None"

s2mel:
  dit_type: DiT
  reg_loss_type: l1
  use_gpt_latent: false
  inference_steps: 25
  inference_cfg_rate: 0.7
  length_ratio: 1.72
  style_encoder:
    dim: 192
  length_regulator:
    channels: 512
    is_discrete: false
    in_channels: 1024
    content_codebook_size: 8192
    sampling_ratios: [1, 1, 1, 1]
    n_codebooks: 1
    quantizer_dropout: 0.0
    f0_condition: false
    n_f0_bins: 512
  DiT:
    hidden_dim: 512
    num_heads: 8
    depth: 13
    class_dropout_prob: 0.1
    block_size: 8192
    in_channels: 80
    style_condition: true
    final_layer_type: wavenet
    content_dim: 512
    content_codebook_size: 1024
    content_type: continuous
    is_causal: false
    long_skip_connection: true
    zero_prompt_speech_token: false
    time_as_token: false
    style_as_token: false
    uvit_skip_connection: true
  wavenet:
    hidden_dim: 512
    num_layers: 8
    kernel_size: 5
    dilation_rate: 1
    p_dropout: 0.2
    style_condition: true

train:
  output_dir: exp/s2mel_dit
  batch_size: 4
  epochs: 10
  max_steps: 0
  grad_accumulation: 1
  learning_rate: 1.0e-4
  min_learning_rate: 1.0e-5
  lr_scheduler: cosine
  weight_decay: 0.01
  warmup_steps: 1000
  grad_clip: 1.0
  mixed_precision: fp16
  log_interval: 20
  valid_interval: 500
  save_interval: 10000
  archive_save_interval: 0
  keep_last: 5
  resume_from: ""
  no_wandb: false
  wandb_entity: haoyuanhuang22-jcxy
  wandb_project: semantic2mel
  wandb_run_name: s2mel_dit
